name: "tvm-upgrade"
version: 0.1.0
usage: "Please see https://github.com/pallav-trilio/tvm-helm-plugins for usage"
description: "Push chart package to ChartMuseum"
ignoreFlags: false
hooks:
  install: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"
command: $HELM_PLUGIN_DIR/bin/tvm-upgrade