name: "tvm-upgrade"
version: "0.1.0"
usage: "Please see https://github.com/trilioData/helm- for usage"
description: "Push chart package to ChartMuseum"
command: "$HELM_PLUGIN_DIR/bin/tvm-upgrade"
downloaders:
- command: "bin/tvm-upgrade"
useTunnel: false
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
